image: node:14
stages:
    - test
    - deploy

test:
    stage: test
    script:
        - npm install
        - npm test

deploy:
    stage: deploy
    script:
        - npm install
        - npm start
    only:
        - master