image: node:14
stages:
    - test
    - docker
    - deploy

test:
    stage: test
    script:
        - npm install
        - npm test

docker:
    stage: docker
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    script:
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    only: 
        - development

deploy:
    stage: deploy
    script:
        - npm install
    only:
        - master